apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oqu99mf0t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oqu99mf0t-nodejs 
  name: oqu99mf0t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oqu99mf0t-nodejs 
